buildscript {
    repositories {
        mavenCentral()
        google()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.7.3'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:2.0.21"

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenCentral()
        google()
    }
}

apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
apply plugin: 'maven-publish'
apply plugin: 'jacoco'

jacoco {
    toolVersion = "0.8.12"
}

def getVersionName = { ->
    return versName
}

def getArtifactId = { ->
    return "payzone-ts-client-android" // Replace with library name ID
}

android {
    namespace 'com.payzone.transaction.client'
    compileSdk 35

    defaultConfig {
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName versName
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            debuggable true
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
    testOptions {
        unitTests.returnDefaultValues = true
    }
    useLibrary 'android.test.mock'
    tasks.register("versionName") {
        println versName
    }
    tasks.register("appname") {
        println "${getArtifactId()}-${versName}"
    }
}

base {
    archivesName = "${getArtifactId()}-${versName}"
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib:2.0.21"
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.11.0"
    implementation 'androidx.test:monitor:1.8.0'
    implementation 'androidx.test.ext:junit:1.3.0'
    testImplementation 'junit:junit:4.13.2'
    testImplementation 'androidx.test:core:1.7.0'
    // Optional -- Mockito framework
    testImplementation 'org.mockito:mockito-core:5.14.2'
    testImplementation 'androidx.test.ext:junit:1.1.5'
}

task jacocoTestReport(type: JacocoReport, dependsOn: 'testDebugUnitTest') {
    reports {
        xml.required = true
        html.required = true
    }
    def fileFilter = ['**/R.class', '**/R$*.class', '**/BuildConfig.*', '**/Manifest*.*', '**/*Test*.*', 'android/**/*.*']
    classDirectories.setFrom(fileTree(dir: "${buildDir}/tmp/kotlin-classes/debug", excludes: fileFilter))
    sourceDirectories.setFrom(files(["${projectDir}/src/main/java"]))
    executionData.setFrom(files("${buildDir}/jacoco/testDebugUnitTest.exec"))
}

def githubProperties = new Properties()
if (rootProject.file("github.properties").exists()) {
    githubProperties.load(new FileInputStream(rootProject.file("github.properties")))
}

publishing {
    publications {
        bar(MavenPublication) {
            groupId 'com.payzone.transaction.client' // Replace with group ID
            artifactId getArtifactId()
            version getVersionName()
            artifact("$buildDir/outputs/aar/${getArtifactId()}-${getVersionName()}-release.aar")
        }
    }

    repositories {
        maven {
            name = "GitHubPackages"
            /** Configure path of your package repository on Github
             *  Replace GITHUB_USERID with your/organisation Github userID and REPOSITORY with the repository name on GitHub
             */
            url = uri("https://maven.pkg.github.com/Payzone-UK/payzone-ts-client-android")

            credentials {
                /**Create github.properties in root project folder file with gpr.usr=GITHUB_USER_ID  & gpr.key=PERSONAL_ACCESS_TOKEN**/
                username = githubProperties['gpr.usr'] ?: System.getenv("GITHUB_ACTOR")
                password = githubProperties['gpr.key'] ?: System.getenv("GITHUB_TOKEN")
            }
        }
    }
}