name: Android Build and Release

on:
  push:
    branches:
      - main
      - master
      - "test/**"

  pull_request:
    branches:
      - develop

jobs:
  android_build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Create github.properties file
        run: |
          touch github.properties
          echo gpr.usr=${{ secrets.GPR_USER }} >> github.properties
          echo gpr.key=${{ secrets.GPR_API_KEY }} >> github.properties
          cat github.properties

      - name: Run unit tests
        run: ./gradlew test

      - name: Upload test report directory
        uses: actions/upload-artifact@v4
        with:
          name: TestResults
          path: build/reports/tests/testDebugUnitTest/

      - name: Run lint
        run: ./gradlew lint

      - name: Upload lint report
        uses: actions/upload-artifact@v4
        with:
          name: LintResult
          path: build/reports/lint-results*.html

  validate_pr:
    if: github.event_name == 'pull_request' && github.base_ref == 'develop'
    needs: android_build
    runs-on: ubuntu-latest
    steps:
      - run: echo "No artifact needed for pull requests."

  test_candidate:
    if: startsWith(github.ref_name, 'test/')
    needs: android_build
    runs-on: ubuntu-latest

    steps:
      - name: Get branch name
        id: extract_branch
        run: |
          echo "branch=$(echo ${GITHUB_REF##*/})" >>$GITHUB_OUTPUT
      - name: Build with Gradle
        run: ./gradlew -PverName=${{steps.extract_branch.outputs.branch}} clean build
      - name: Set App name
        run: |
          echo "APP_NAME=$(basename  `ls build/outputs/aar/*debug.aar | head -n 1`)" >> $GITHUB_ENV
        id:
          app_name
      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: ${{env.APP_NAME}}
          path: build/outputs/aar/${{env.APP_NAME}}

  release_candidate:
    if: contains(fromJson('["main", "master"]'), github.ref_name)
    needs: [android_build]
    runs-on: ubuntu-latest

    steps:
      - name: Retrieve Version name
        run: |
          echo "::set-output name=VERSION_NAME::$(${{github.workspace}}/gradlew -q versionName)"
        id: app_version
      - name: Set Version name
        run: |
          echo "VERSION_NAME=${{steps.app_version.outputs.VERSION_NAME}}" >> $GITHUB_ENV
      - name: Build with Gradle
        run: ./gradlew build
      - name: Set App name
        run: |
          echo "APP_NAME=$(basename `ls build/outputs/aar/*release.aar | head -n 1`)" >> $GITHUB_ENV
          echo "AppName is $APP_NAME"
        id:
          app_name
#      - name: Create Release
#        id: create_release
#        uses: actions/create-release@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          tag_name: v.${{env.VERSION_NAME}}
#          release_name: Release  ${{env.VERSION_NAME}}
#      - name: Upload Release Package
#        id: upload_release_asset
#        uses: actions/upload-release-asset@v1.0.1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          upload_url: ${{ steps.create_release.outputs.upload_url }}
#          asset_path: build/outputs/aar/${{env.APP_NAME}}
#          asset_name: ${{env.APP_NAME}}
#          asset_content_type: application/zip
#      - name: Publish package
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        run: ./gradlew publish