name: Release Candidate

on:
  push:
    branches:
      - main
      - master

jobs:
  publish_aar:
    uses: ./.github/workflows/android-build.yml
    with:
      build_type: release
      upload_artifacts: true
      create_release: true