name: Test Candidate

on:
  push:
    branches: [ "test/**" ]

jobs:
  build_aar:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Create github.properties file
        run: |
          touch github.properties
          echo gpr.usr=${{ secrets.GPR_USER }} >> github.properties
          echo gpr.key=${{ secrets.GPR_API_KEY }} >> github.properties
          echo "cat github.properties"
          cat github.properties
      - name: Run unit tests
        run: ./gradlew test
      - name: Upload test report directory
        uses: actions/upload-artifact@v2
        with:
          name: TestResults
          path: build/reports/tests/testDebugUnitTest/
      - name: Run lint
        run: ./gradlew lint
      - name: Upload lint report
        uses: actions/upload-artifact@v2
        with:
          name: LintResult
          path: build/reports/lint-results*.html
      - name: Get branch name
        id: extract_branch
        run: |
          echo "::set-output name=branch::$(echo ${GITHUB_REF##*/})"
      - name: Build with Gradle
        run: ./gradlew -PverName=${{steps.extract_branch.outputs.branch}} clean build
      - name: Set App name
        run: |
          echo "APP_NAME=$(basename  `ls build/outputs/aar/*debug.aar | head -n 1`)" >> $GITHUB_ENV
        id:
          app_name
      - name: Upload package
        uses: actions/upload-artifact@v1
        with:
          name: ${{env.APP_NAME}}
          path: build/outputs/aar/${{env.APP_NAME}}
